coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0.1%
        flags:
          - unit
          - nightly
      unit:
        target: auto
        flags:
          - unit
      nightly:
        target: auto
        flags:
          - nightly

flags:
  unit:
    carryforward: false
  nightly:
    carryforward: true
