name: jwst
dependencies:
  - python=3.6.6
  - setuptools
  - pip:
    - numpy
    - sphinx
    - sphinxcontrib-programoutput
    - sphinx-automodapi
    - sphinx_rtd_theme
    - stsci_rtd_theme
    - matplotlib
    - astropy
    - asdf
    - crds
    - scipy
    - drizzle
    - gwcs
    - jsonschema
    - jplephem
    - namedlist
    - photutils
    - spherical-geometry
    - stsci.image
    - stsci.imagestats
    - stsci.stimage
    - stsci.tools
    - verhawk
    - pytest
