name: jwst
dependencies:
  - python=3.6
  - setuptools
  - numpy=1.15
  - pip:
    - astropy
    - asdf
    - crds
    - scipy
    - drizzle
    - gwcs
    - jsonschema
    - jplephem
    - namedlist
    - photutils
    - spherical-geometry
    - stsci.image
    - stsci.imagestats
    - stsci.stimage
    - stsci.tools
    - verhawk
    - pytest
    - sphinxcontrib-programoutput
    - sphinx-automodapi
    - stsci_rtd_theme
    - matplotlib
