name: jwst
dependencies:
  - "python>=3.5"
  - setuptools
  - numpy
  - pip:
    - sphinx
    - sphinxcontrib-programoutput
    - sphinx-automodapi
    - sphinx_rtd_theme
    - stsci_rtd_theme
    - matplotlib
    - "astropy>=3.1"
    - asdf
    - crds
    - scipy
    - drizzle
    - gwcs
    - jsonschema
    - jplephem
    - namedlist
    - photutils
    - spherical-geometry
    - stsci.image
    - stsci.imagestats
    - stsci.stimage
    - stsci.tools
    - verhawk
    - pytest
