dist: xenial
language: python
python: 3.6.8

sudo: false
#os: linux

# The apt packages below are needed for sphinx builds
addons:
  apt:
    packages:
      - texlive-latex-extra
      - dvipng
      - graphviz
      - libblas3
      - liblapack3
      - liblapack-dev
      - libblas-dev

env:
  global:
    - CRDS_SERVER_URL='https://jwst-crds.stsci.edu'
    - CRDS_PATH='/tmp/crds_cache'
    - NUMPY="numpy~=1.16"
    - TEST_COMMAND='pytest'

matrix:
  # Don't wait for allowed failures
  fast_finish: true

  include:
    - env: PIP_DEPENDENCIES=".[test]"

    - python: 3.7
      env: PIP_DEPENDENCIES=".[test]"

    - env: PIP_DEPENDENCIES="-r requirements-dev.txt .[test]"
           NUMPY="cython git+https://github.com/numpy/numpy"

    - python: 3.7
      env: PIP_DEPENDENCIES="-r requirements-dev.txt .[test]"
           NUMPY="cython git+https://github.com/numpy/numpy"

    - python: 3.8-dev
      env: PIP_DEPENDENCIES=".[test]"

    # Test with latest delivered CRDS_CONTEXT, as in regressions tests
    - env: CRDS_CONTEXT="jwst-edit"
           PIP_DEPENDENCIES=".[test]"

    # Build sphinx documentation with warnings
    - env: TEST_COMMAND="make --directory=docs html"
           PIP_DEPENDENCIES=".[docs]"

    # PEP8 check
    - env: TEST_COMMAND="flake8"
           PIP_DEPENDENCIES="flake8"

  allow_failures:
    - env: PIP_DEPENDENCIES="-r requirements-dev.txt .[test]"
           NUMPY="cython git+https://github.com/numpy/numpy"

    - python: 3.7
      env: PIP_DEPENDENCIES="-r requirements-dev.txt .[test]"
           NUMPY="cython git+https://github.com/numpy/numpy"

    - python: 3.8-dev
      env: PIP_DEPENDENCIES=".[test]"

    - env: CRDS_CONTEXT="jwst-edit"
           PIP_DEPENDENCIES=".[test]"

install:
  - pip install $NUMPY
  - pip install $PIP_DEPENDENCIES

script: $TEST_COMMAND
