os: linux
dist: xenial
language: python
python: 3.7.7

env:
  global:
    - CRDS_SERVER_URL="https://jwst-crds.stsci.edu"
    - CRDS_PATH="/tmp/crds_cache"
    - CRDS_CLIENT_RETRY_COUNT=3
    - CRDS_CLIENT_RETRY_DELAY_SECONDS=20
    - TEST_COMMAND="pytest --cov-report=xml --cov=./"
    - PIP_DEPENDENCIES=".[test]"

jobs:
  # Don't wait for allowed failures
  fast_finish: true

  include:
    - python: 3.6.10
    - python: 3.7.7
    - python: 3.8.2

    - env: PIP_DEPENDENCIES="numpy~=1.16.0 .[test]"
      python: 3.6.10

    - env: PIP_DEPENDENCIES="numpy~=1.17.0 .[test]"

    - env: PIP_DEPENDENCIES="-r requirements-min.txt .[test]"
      python: 3.6.0
      PRE_INSTALL1="pip install . --no-deps"
      PRE_INSTALL2="minimum_deps"

    # Test with SDP pinned dependencies
    - env: PIP_DEPENDENCIES="-r requirements-sdp.txt .[test]"
      python: 3.7.7

    # Test with dev dependencies
    - env: PIP_DEPENDENCIES="-r requirements-dev.txt .[test]"
      python: 3.8.2

    # Test with latest delivered CRDS_CONTEXT, as in regressions tests
    - env: CRDS_CONTEXT="jwst-edit"
           PIP_DEPENDENCIES=".[test]"

    # Build documentation
    - env: PIP_DEPENDENCIES=".[docs]"
           TEST_COMMAND="make --directory=docs html"
      addons:
        apt:
          packages:
            - texlive-latex-extra
            - dvipng
            - graphviz

    # PEP8 check
    - env: TEST_COMMAND="flake8"
           PIP_DEPENDENCIES="flake8"

  allow_failures:
    - env: PIP_DEPENDENCIES="-r requirements-dev.txt .[test]"
      python: 3.8.2

    - env: CRDS_CONTEXT="jwst-edit"
           PIP_DEPENDENCIES=".[test]"

install:
  - if [[ ${PRE_INSTALL1} ]]; then $PRE_INSTALL1; fi
  - if [[ ${PRE_INSTALL2} ]]; then $PRE_INSTALL2; fi
  - pip install $PIP_DEPENDENCIES

script:
  - $TEST_COMMAND

after_success:
  - if [[ ${TEST_COMMAND} =~ ^pytest ]]; then codecov -F unit; fi
