os: linux
dist: xenial
language: python
python: 3.8.5

env:
  global:
    - CRDS_SERVER_URL=https://jwst-crds.stsci.edu
    - CRDS_PATH=/tmp/crds_cache
    - CRDS_CLIENT_RETRY_COUNT=3
    - CRDS_CLIENT_RETRY_DELAY_SECONDS=20

jobs:
  include:
    - name: Time CRDS downloads

install:
  - pip install crds==7.6.0

script:
  - time python -c "import crds; crds.client.api.dump_mappings('jwst_0641.pmap')"
  - time python -c "import crds; crds.client.api.dump_references('jwst_0641.pmap', ['jwst_miri_dark_0050.fits'])"
