os: linux
dist: xenial
language: python
python: 3.9.0

env:
  global:
    - CRDS_SERVER_URL=https://jwst-crds.stsci.edu
    - CRDS_PATH=/tmp/crds_cache
    - CRDS_CLIENT_RETRY_COUNT=3
    - CRDS_CLIENT_RETRY_DELAY_SECONDS=20

cache:
  - pip
  - directories:
    - /tmp/crds_cache

jobs:
  # Don't wait for allowed failures
  fast_finish: true

  include:
    - name: Latest dependency versions w/coverage
      env: TOXENV=py39-cov-report

    - name: Oldest dependency versions
      python: 3.7.9
      env: TOXENV=py37-oldestdeps-cov-report

    - name: SDP dependencies in requirements-sdp.txt
      python: 3.8.6
      env:
        - CRDS_CONTEXT=jwst-edit
        - TOXENV=sdpdeps

    - name: Dev dependencies in requirements-dev.txt
      env: TOXENV=devdeps

    - name: Warnings treated as Exceptions
      env: TOXENV=warnings

    - name: Documentation build
      env: TOXENV=docs
      addons:
        apt:
          packages:
            - texlive-latex-extra
            - dvipng
            - graphviz

    - name: Code style check
      env: TOXENV=style

    - name: Verify install_requires in setup.py
      env: TOXENV=verify-install-requires

    - name: Build distribution
      env: TOXENV=twine

    - name: Security check
      env: TOXENV=security

  allow_failures:
    - name: Dev dependencies in requirements-dev.txt
      env: TOXENV=devdeps

    - name: Warnings treated as Exceptions
      env: TOXENV=warnings

install:
  - pip install tox

script:
  - tox
