dist: xenial
language: python
python: 3.6.8

sudo: false
#os: linux

# The apt packages below are needed for sphinx builds
addons:
  apt:
    packages:
      - texlive-latex-extra
      - dvipng
      - graphviz

env:
  global:
    - CRDS_SERVER_URL='https://jwst-crds.stsci.edu'
    - CRDS_PATH='/tmp/crds_cache'
    - NUMPY_VERSION=1.16

matrix:
  # Don't wait for allowed failures
  fast_finish: true
  include:
    # Run tests
    - env: TEST_COMMAND='python setup.py test'
           PIP_DEPENDENCIES='.[test]'

    # Test with python 3.7
    - python: 3.7
      env: TEST_COMMAND='python setup.py test'
           PIP_DEPENDENCIES='.[test]'

    # Test with dev dependencies
    - env: PIP_DEPENDENCIES="-r requirements-dev.txt .[test]"
           TEST_COMMAND='python setup.py test'

    # Test with python 3.7 and dev dependencies
    - python: 3.7
      env: PIP_DEPENDENCIES="-r requirements-dev.txt .[test]"
           TEST_COMMAND='python setup.py test'

    # Test with latest delivered CRDS_CONTEXT, as in regressions tests
    - env: CRDS_CONTEXT="jwst-edit"
           TEST_COMMAND='python setup.py test'

    # Build sphinx documentation with warnings
    - env: TEST_COMMAND='python setup.py build_sphinx'
           PIP_DEPENDENCIES='.[docs]'

    # PEP8 check
    - env: TEST_COMMAND='flake8 jwst'
           PIP_DEPENDENCIES='flake8'

  allow_failures:
    - env: PIP_DEPENDENCIES="-r requirements-dev.txt .[test]"
           TEST_COMMAND='python setup.py test'

    - python: 3.7
      env: PIP_DEPENDENCIES="-r requirements-dev.txt .[test]"
           TEST_COMMAND='python setup.py test'

    - env: CRDS_CONTEXT="jwst-edit"
           TEST_COMMAND='python setup.py test'

install:
  - pip install numpy~=$NUMPY_VERSION
  - if [[ -n $PIP_DEPENDENCIES ]]; then pip install $PIP_DEPENDENCIES; fi

script: $TEST_COMMAND
