dist: xenial
language: python
python: 3.6.8

sudo: false
#os: linux

# The apt packages below are needed for sphinx builds
addons:
  apt:
    packages:
      - texlive-latex-extra
      - dvipng
      - graphviz

env:
  global:
    - CRDS_SERVER_URL='https://jwst-crds.stsci.edu'
    - CRDS_PATH='/tmp/crds_cache'
    - NUMPY_VERSION=1.17
    - TEST_COMMAND='pytest --cov=./'

matrix:
  # Don't wait for allowed failures
  fast_finish: true

  include:
    # Run tests
    - env: PIP_DEPENDENCIES='.[test]'

    # Test with python 3.7
    - python: 3.7
      env: PIP_DEPENDENCIES='.[test]'

    # Test with numpy 1.16
    - env: NUMPY_VERSION=1.16

    # Test with SDP pinned dependencies
    - env: PIP_DEPENDENCIES='-r requirements-sdp.txt .'

    # Test with dev dependencies
    - env: PIP_DEPENDENCIES="-r requirements-dev.txt .[test]"

    # Test with python 3.7 and dev dependencies
    - python: 3.7
      env: PIP_DEPENDENCIES="-r requirements-dev.txt .[test]"

    # Test with latest delivered CRDS_CONTEXT, as in regressions tests
    - env: CRDS_CONTEXT="jwst-edit"
           PIP_DEPENDENCIES=".[test]"

    # Build sphinx documentation with warnings
    - env: TEST_COMMAND='make --directory=docs html'
           PIP_DEPENDENCIES='.[docs]'

    # PEP8 check
    - env: TEST_COMMAND='flake8 jwst'
           PIP_DEPENDENCIES='flake8'

  allow_failures:
    - env: PIP_DEPENDENCIES="-r requirements-dev.txt .[test]"

    - python: 3.7
      env: PIP_DEPENDENCIES="-r requirements-dev.txt .[test]"

    - env: CRDS_CONTEXT="jwst-edit"
           PIP_DEPENDENCIES=".[test]"

install:
  - pip install numpy~=$NUMPY_VERSION
  - pip install $PIP_DEPENDENCIES

script:
  - $TEST_COMMAND

after_script:
  - if [ "${TEST_COMMAND:0:6}" = "pytest" ]; then codecov; fi
