language: python
dist: xenial
python:
  - "3.6"
sudo: false

# The apt packages below are needed for sphinx builds
addons:
  apt:
    packages:
      - texlive-latex-extra
      - dvipng
      - graphviz

env:
  global:
    - CRDS_SERVER_URL='https://jwst-crds.stsci.edu'
    - CRDS_PATH='/tmp/crds_cache'
    - PIP_INDEX="https://bytesalad.stsci.edu/artifactory/api/pypi/datb-pypi-virtual/simple"
    - PIP_INSTALL_ARGS=" --index-url ${pip_index} --progress-bar=off "


matrix:
  # Don't wait for allowed failures
  fast_finish: true
  include:
    # Run tests
    - env: TEST_COMMAND='python setup.py test'
           PIP_DEPENDENCIES='.[test]'
    # Build sphinx documentation with warnings
    - env: TEST_COMMAND='python setup.py build_sphinx -W'
           PIP_DEPENDENCIES='.[docs]'
    # PEP8 check
    - env: TEST_COMMAND='flake8 --count --select=F, E101, E111, E112, E113, E401, E402, E711, E722 --max-line-length=110 jwst'
    # Strict PEP8 check, an allowed failure below
    - env: TEST_COMMAND='flake8 --count jwst'

  allow_failures:
    - env: TEST_COMMAND='flake8 --count jwst'

install:
  - pip install numpy~=1.16
  - if [[ -n $PIP_DEPENDENCIES ]]; then pip install $PIP_INSTALL_ARGS -e $PIP_DEPENDENCIES; fi
  - python setup.py develop

script:
  - $TEST_COMMAND
