os: linux
dist: xenial
language: python
python: 3.8.5

env:
  global:
    - CRDS_SERVER_URL=https://jwst-crds.stsci.edu
    - CRDS_PATH=/tmp/crds_cache
    - CRDS_CLIENT_RETRY_COUNT=3
    - CRDS_CLIENT_RETRY_DELAY_SECONDS=20

addons:
  apt:
    packages:
      - traceroute

jobs:
  include:
    - name: Time CRDS downloads

install:
  - pip install crds==7.6.0

script:
  - traceroute jwst-crds.stsci.edu
