os: linux
dist: xenial
language: python
python: 3.7.7

env:
  global:
    - CRDS_SERVER_URL=https://jwst-crds.stsci.edu
    - CRDS_PATH=/tmp/crds_cache
    - CRDS_CLIENT_RETRY_COUNT=3
    - CRDS_CLIENT_RETRY_DELAY_SECONDS=20
    - TEST_COMMAND="pytest --cov-report=xml --cov=./"
    - PIP_DEPENDENCIES=.[test]

jobs:
  # Don't wait for allowed failures
  fast_finish: true

  include:
    - python: 3.7.7

    - python: 3.8.2

    - env: PIP_DEPENDENCIES="numpy~=1.17.0 .[test]"
      name: Python 3.7.x, Numpy 1.17.x

    - env: PIP_DEPENDENCIES="-r requirements-min.txt .[test]"
      python: 3.6.10
      name: Dependencies set at minimum version allowed in setup.py

    - env: PIP_DEPENDENCIES="-r requirements-sdp.txt .[test]"
      python: 3.7.7
      name: SDP dependencies set in requirements-sdp.txt

    - env: PIP_DEPENDENCIES="-r requirements-dev.txt .[test]"
      python: 3.8.2
      name: Dev dependencies specified in requirements-dev.txt

    - env: CRDS_CONTEXT=jwst-edit
      name: Latest delivered CRDS_CONTEXT=jwst-edit

    - env: PIP_DEPENDENCIES=.[docs]
           TEST_COMMAND="make --directory=docs html"
      name: Documentation
      addons:
        apt:
          packages:
            - graphviz

    - env: TEST_COMMAND=flake8
           PIP_DEPENDENCIES=flake8
      name: Code style check

  allow_failures:
    - env: PIP_DEPENDENCIES="-r requirements-dev.txt .[test]"
      python: 3.8.2
      name: Dev dependencies specified in requirements-dev.txt

    - env: CRDS_CONTEXT=jwst-edit
      name: Latest delivered CRDS_CONTEXT=jwst-edit

install:
  - pip install . --no-deps
  - minimum_deps
  - pip install $PIP_DEPENDENCIES

script:
  - $TEST_COMMAND

after_success:
  - if [[ ${TEST_COMMAND} =~ ^pytest ]]; then
      codecov -F unit;
    fi
