dist: xenial
language: python
python: 3.7.5

sudo: false
#os: linux

# The apt packages below are needed for sphinx builds
addons:
  apt:
    packages:
      - texlive-latex-extra
      - dvipng
      - graphviz
      - liblapack-dev

# TODO: Unlock jwst/regtest
# TODO: Unlock coverage
env:
  global:
    - CRDS_SERVER_URL='https://jwst-crds.stsci.edu'
    - CRDS_PATH='/tmp/crds_cache'
    - TEST_COMMAND='pytest --cov=./ jwst/regtest'

matrix:
  # Don't wait for allowed failures
  fast_finish: true

  include:
    - python: 3.6.8
      env: PIP_DEPENDENCIES='.[test]'

    - env: PIP_DEPENDENCIES='.[test]'

    - python: 3.8
      env: PIP_DEPENDENCIES='.[test]'

    - env: PIP_DEPENDENCIES='numpy~=1.16.0 .[test]'
      python: 3.6.8

    # Test with SDP pinned dependencies
    - env: PIP_DEPENDENCIES='-r requirements-sdp.txt .'
      python: 3.7.4

    # Test with dev dependencies
    - env: PIP_DEPENDENCIES="-r requirements-dev.txt .[test]"

    # Test with latest delivered CRDS_CONTEXT, as in regressions tests
    - env: CRDS_CONTEXT="jwst-edit"
           PIP_DEPENDENCIES=".[test]"

    # Build sphinx documentation with warnings
    - env: TEST_COMMAND='make --directory=docs html'
           PIP_DEPENDENCIES='.[docs]'

    # PEP8 check
    - env: TEST_COMMAND='flake8 jwst'
           PIP_DEPENDENCIES='flake8'

  allow_failures:
    - python: 3.8
      env: PIP_DEPENDENCIES='.[test]'

    - env: PIP_DEPENDENCIES="-r requirements-dev.txt .[test]"

    - env: CRDS_CONTEXT="jwst-edit"
           PIP_DEPENDENCIES=".[test]"

install:
  - pip install $PIP_DEPENDENCIES

script:
  - $TEST_COMMAND

#after_script:
#  - if [ "${TEST_COMMAND:0:6}" = "pytest" ]; then codecov; fi
