language: c

os:
    - linux

stage: Comprehensive tests

sudo: false

# The apt packages below are needed for sphinx builds, which can no longer
# be installed with sudo apt-get.
addons:
    apt:
        packages:
            - graphviz
            - texlive-latex-extra
            - dvipng

env:
    global:
        - MAIN_CMD='python setup.py'
        - CONDA_CHANNELS='http://ssb.stsci.edu/conda-dev'
        - CONDA_DEPENDENCIES='pytest jwst sphinx'
        - CONDA_JWST_DEPENDENCIES='pytest jwst sphinx'
        - PIP_DEPENDENCIES=''
        - CRDS_SERVER_URL='https://jwst-crds.stsci.edu'
        - CRDS_PATH='/tmp/crds_cache'
        - NUMPY_VERSION=1.12

    matrix:
        - PYTHON_VERSION=2.7 SETUP_CMD='install'
        - PYTHON_VERSION=2.7 SETUP_CMD='test'
        - PYTHON_VERSION=3.5 SETUP_CMD='install'
        - PYTHON_VERSION=3.5 SETUP_CMD='test'

stages:
   # Do the style check and a single test job, don't proceed if it fails
   - name: Initial tests
   # Do the rest of the tests
   - name: Comprehensive tests

matrix:

    # Don't wait for allowed failures
    fast_finish: true

    include:
        # Test numpy 1.13
        #- os: linux
        #  env: PYTHON_VERSION=3.5 NUMPY_VERSION=1.13 SETUP_CMD='test'

        # PEP8 check with flake8 (only once, i.e. "os: linux")
        - os: linux
          stage: Initial tests
          env: PYTHON_VERSION=3.5 MAIN_CMD='flake8 --count'
               SETUP_CMD='jwst' TEST_CMD='flake8 --version'
               CONDA_DEPENDENCIES=$CONDA_JWST_DEPENDENCIES

        # build sphinx documentation with warnings
        - os: linux
          env: PYTHON_VERSION=3.5
               SETUP_CMD='build_docs'
               CONDA_DEPENDENCIES=$CONDA_JWST_DEPENDENCIES
               PIP_DEPENDENCIES='sphinx_rtd_theme sphinx-automodapi'

install:
    - git clone git://github.com/astropy/ci-helpers.git
    - source ci-helpers/travis/setup_conda_$TRAVIS_OS_NAME.sh

after_install:
    - conda list astropy

script:
    - $MAIN_CMD $SETUP_CMD
