language: c

os:
    - linux

sudo: false

# The apt packages below are needed for sphinx builds, which can no longer
# be installed with sudo apt-get.
addons:
    apt:
        packages:
            - texlive-latex-extra
            - dvipng
            - graphviz

env:
    global:
        - CONDA_CHANNELS='http://ssb.stsci.edu/astroconda-dev'
        - CONDA_DEPENDENCIES="asdf
                              astropy
                              crds
                              drizzle
                              flake8
                              gwcs
                              jsonschema
                              jplephem
                              matplotlib
                              photutils
                              scipy
                              spherical-geometry
                              stsci.image
                              stsci.imagestats
                              stsci.stimage
                              verhawk"
        - CONDA_DOCS_DEPENDENCIES='sphinx graphviz'
        - CRDS_SERVER_URL='https://jwst-crds.stsci.edu'
        - CRDS_PATH='/tmp/crds_cache'
        - MAIN_CMD='python setup.py'
        - MC_URL=https://repo.continuum.io/miniconda
        - PIP_DEPENDENCIES='.[test]'
        - PYTHON_VERSION=3.6
        - NUMPY_VERSION=1.15

    matrix:
        - SETUP_CMD='install'
        - SETUP_CMD='test'

matrix:

    # Don't wait for allowed failures
    fast_finish: true

    include:

        # PEP8 check with flake8 (only once, i.e. "os: linux")
        - os: linux
          env: MAIN_CMD='flake8 --count'
               SETUP_CMD='jwst'
               PIP_DEPENDENCIES='.'

        # build sphinx documentation with warnings
        - os: linux
          env: SETUP_CMD='build_sphinx -W'
               CONDA_DEPENDENCIES="$CONDA_DEPENDENCIES"
               PIP_DEPENDENCIES='.[docs]'
        - os: linux
          env: MAIN_CMD='flake8 --count --select=F, E101, E111, E112, E113, E401, E402, E711, E722 --max-line-length=110'
               SETUP_CMD='jwst'

    allow_failures:
        # PEP8 will fail for numerous reasons. Ignore it.
        - env: MAIN_CMD='flake8 --count'
               SETUP_CMD='jwst'
               PIP_DEPENDENCIES='.'

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then MC_INST=Miniconda-latest-Linux-x86_64.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then MC_INST=Miniconda-latest-MacOSX-x86_64.sh; fi
  - curl -LO "$MC_URL/$MC_INST"
  - bash $MC_INST -b -p $HOME/miniconda
  - export PATH=$HOME/miniconda/bin:$PATH
  - conda config --set always_yes yes --set changeps1 no
  - for channel in $CONDA_CHANNELS; do conda config --add channels "$channel"; done
  - conda update -y conda
  - conda create -n test -q python=$PYTHON_VERSION numpy=$NUMPY_VERSION $CONDA_DEPENDENCIES
  - source activate test
  - if [[ -n $PIP_DEPENDENCIES ]]; then pip install -q -e $PIP_DEPENDENCIES; fi

after_install:
  - conda list astropy

script:
  - $MAIN_CMD $SETUP_CMD
