language: c

os:
    - linux

sudo: false

# The apt packages below are needed for sphinx builds, which can no longer
# be installed with sudo apt-get.
addons:
    apt:
        packages:
            - graphviz
            - texlive-latex-extra
            - dvipng

env:
    global:
        - MAIN_CMD='python setup.py'
        - CONDA_CHANNELS='http://ssb.stsci.edu/conda-dev'
        - CONDA_DEPENDENCIES='pytest jwst sphinx'
        - CONDA_JWST_DEPENDENCIES='pytest jwst sphinx'
        - PIP_DEPENDENCIES=''
        - CRDS_SERVER_URL='https://jwst-crds.stsci.edu'
        - CRDS_PATH='/tmp/crds_cache'
        - PYTHON_VERSION=3.6
        - NUMPY_VERSION=stable
        - ASTROPY_VERSION=development

    matrix:
        - SETUP_CMD='install'
        - SETUP_CMD='test'
        # These will no longer work unless we add an explicit dependency on asdf-1.3.1
        #- PYTHON_VERSION=2.7 SETUP_CMD='install' ASTROPY_VERSION=stable
        #- PYTHON_VERSION=2.7 SETUP_CMD='test' ASTROPY_VERSION=stable

matrix:

    # Don't wait for allowed failures
    fast_finish: true

    include:

        # PEP8 check with flake8 (only once, i.e. "os: linux")
        - os: linux
          env: MAIN_CMD='flake8 --count'
               SETUP_CMD='jwst' TEST_CMD='flake8 --version'
               CONDA_DEPENDENCIES=$CONDA_JWST_DEPENDENCIES

        # build sphinx documentation with warnings
        - os: linux
          env: SETUP_CMD='build_sphinx'
               CONDA_DEPENDENCIES=$CONDA_JWST_DEPENDENCIES
               PIP_DEPENDENCIES='sphinx_rtd_theme stsci_rtd_theme sphinx-automodapi'

    allow_failures:
        # PEP8 will fail for numerous reasons. Ignore it.
        - env: MAIN_CMD='flake8 --count'
               SETUP_CMD='jwst' TEST_CMD='flake8 --version'
               CONDA_DEPENDENCIES=$CONDA_JWST_DEPENDENCIES

install:
    - git clone git://github.com/astropy/ci-helpers.git
    - source ci-helpers/travis/setup_conda_$TRAVIS_OS_NAME.sh

after_install:
    - conda list astropy

script:
    - $MAIN_CMD $SETUP_CMD
