name: CI

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:

env:
  CRDS_SERVER_URL: https://jwst-crds.stsci.edu
  CRDS_PATH: ~/crds_cache
  CRDS_CLIENT_RETRY_COUNT: 3
  CRDS_CLIENT_RETRY_DELAY_SECONDS: 20

jobs:
  tox:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Latest dependency versions w/coverage
            os: ubuntu-latest
            python-version: 3.9
            toxenv: py39-cov-report

          - name: Oldest dependency versions
            os: ubuntu-latest
            python-version: 3.7
            toxenv: py37-oldestdeps-cov-report

          - name: SDP dependencies in requirements-sdp.txt
            os: ubuntu-latest
            python-version: 3.8
            toxenv: sdpdeps
            env:
              CRDS_CONTEXT: jwst-edit

          - name: Verify install_requires in setup.py
            os: ubuntu-latest
            python-version: 3.9
            toxenv: verify-install-requires

          - name: Build distribution
            os: ubuntu-latest
            python-version: 3.9
            toxenv: twine

          - name: Code style check
            os: ubuntu-latest
            python-version: 3.9
            toxenv: style

          - name: Security audit
            os: ubuntu-latest
            python-version: 3.9
            toxenv: security

          - name: macOS
            os: macos-latest
            python-version: 3.9
            toxenv: py39
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip
      - name: Get pip cache dir
        id: pip-cache
        run: |
          echo "::set-output name=dir::$(pip cache dir)"
      - name: pip cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-pip-${{ hashFiles('setup.cfg') }}-${{ hashFiles('**/requirement-sdp.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: CRDS cache
        uses: actions/cache@v2
        with:
          path: ~/crds_cache
          key: crds_cache
          restore-keys: |
            crds_cache
      - name: Install tox
        run: |
          pip install tox
      - name: Run tests
        run: tox -e ${{ matrix.toxenv }}

  # Kept in a separate job because it needs extra system dependencies
  # that can't be installed by tox.
  build-docs:
    name: Build documentation and check warnings
    runs-on: ubuntu-latest
    steps:
      - name: Install system packages
        run: |
          sudo apt-get install graphviz texlive-latex-extra dvipng
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip
      - name: Get pip cache dir
        id: pip-cache
        run: |
          echo "::set-output name=dir::$(pip cache dir)"
      - name: pip cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-pip-${{ hashFiles('setup.cfg') }}-${{ hashFiles('**/requirement-sdp.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install tox
        run: |
          pip install tox
      - name: Run tox
        run: tox -e docs

  # # A matrix of jobs with allowed failures.  Not enabled for now.
  # allowed_failures:
  #   name: ${{ matrix.name }}
  #   runs-on: ${{ matrix.os }}
  #   continue-on-error: ${{ matrix.allowed-failure }}
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       include:
  #         - name: (Allowed Failure) Dev dependencies in requirements-dev.txt
  #           os: ubuntu-latest
  #           allowed-failure: true
  #           python-version: 3.9
  #           toxenv: devdeps

  #         - name: (Allowed Failure) Warnings treated as Exceptions
  #           os: ubuntu-latest
  #           allowed-failure: true
  #           python-version: 3.9
  #           toxenv: warnings
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2
  #       with:
  #         fetch-depth: 0
  #     - name: Set up Python ${{ matrix.python-version }}
  #       uses: actions/setup-python@v2
  #       with:
  #         python-version: ${{ matrix.python-version }}
  #     - name: Install tox
  #       run: |
  #         python -m pip install --upgrade pip
  #         pip install tox
  #     - name: Run tox
  #       run: tox -e ${{ matrix.toxenv }}
